version: "3.8"

services:
  frontend:
    build:
      context: ./docker
      dockerfile: dockerfile-frontend
    init: true
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    # Code wird vom Devcontainer gemountet – kein zusätzliches volumes hier.

networks:
  default:
    driver: bridge