version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: filemate_db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: filemate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/workspaces/filemate/backend
      - .:/workspaces/filemate
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dbuser:dbpass@db:5432/filemate
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: filemate_frontend
    volumes:
      - ./frontend:/workspaces/filemate/frontend
      - /workspaces/filemate/frontend/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:
